---
title: "Exploratory analysis"
output: github_document
date: "2025-10-02"
---


```{r setup, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal()+theme(legend.position = "bottom"))

options(
  ggplot2.continuous.color = "viridis",
   ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


# Load the weather data

```{r}
library(p8105.datasets)
data("weather_df")
weather_df = 
  weather_df |>
  mutate(
    month = lubridate::floor_date(date, unit = "month"))
weather_df
```


## `group_by`

```{r}
weather_df %>%
  group_by(name, month)
```
you can try `ungroup()`


## counting things

count month/name observations

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarise(n_obs = n())
```

we can use `count()`

```{r}
weather_df %>%
  count(name, month, name = "n_obs")
```

**NEVER** use base R's `table`

```{r}
weather_df %>%
  pull(month) %>%
  table()
```


other helpful counters

```{r}
weather_df %>%
  group_by(month) %>%
  summarise(
    n_obs = n(),
    n_days = n_distinct(date))
```


## A digression on 2x2 tables

```{r}
weather_df %>% 
  filter(name != "Molokai_HI") %>%
  mutate(
    cold = case_when(
      tmax < 5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE   ~""
    )
  ) %>%
  group_by(name, cold) %>%
  summarise(count=n())
```



```{r}
weather_df %>% 
  filter(name != "Molokai_HI") %>%
  mutate(
    cold = case_when(
      tmax < 5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE   ~""
    )
  ) %>%
  janitor::tabyl(name, cold)
```













