---
title: "Visualization"
subtitle: "Part II"
output: html_document
date: "2025-09-30"
---

```{r setup}
library(tidyverse)
library(patchwork)
```


# Load the weather data

```{r}
library(p8105.datasets)
data("weather_df")
```


## Remember this plot...?

```{r}
weather_df %>%
  ggplot(aes(x=tmin,y=tmax, color=name)) +
  geom_point(alpha = .5)
```

## Lables

```{r}
weather_df %>%
  ggplot(aes(x=tmin,y=tmax, color=name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maximum daily temperature (C)",
    caption = "Data from rnoaa package; temperature in 2021."
  )
```

## Scales

Start with the same plot

```{r}
weather_df %>%
  ggplot(aes(x=tmin,y=tmax, color=name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maximum daily temperature (C)",
    caption = "Data from rnoaa package; temperature in 2021."
  )+
  scale_x_continuous(
    breaks = c(-15, 0, 15),
    labels = c("-15C", "0", "15")
  )+
  scale_y_continuous(
    position = "right"
  )
```

(可以在scale_y_continuous中使用`trans = "log"`将函数拟合进行转换)


Look at color scales

```{r}
weather_df %>%
  ggplot(aes(x=tmin,y=tmax, color=name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maximum daily temperature (C)",
    caption = "Data from rnoaa package; temperature in 2021."
  )+
  scale_color_hue(
    name = "Location",
    h=c(100,300))
```
(`name = "Location"`:修改颜色图例的标题;
  `h=c(100,300)`:控制颜色的色相范围)

```{r}
weather_df %>%
  ggplot(aes(x=tmin,y=tmax, color=name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maximum daily temperature (C)",
    caption = "Data from rnoaa package; temperature in 2021."
  )+
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE)
```
(这里`color = name`，name是一个离散型变量，因此要加`discrete = TRUE`)




## Themes

Shift the legend:

```{r}
weather_df %>%
  ggplot(aes(x=tmin,y=tmax, color=name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maximum daily temperature (C)",
    caption = "Data from rnoaa package; temperature in 2021."
  )+
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE)+
  theme(legend.position = "bottom")
```

Change the overall theme.
```{r}
weather_df %>%
  ggplot(aes(x=tmin,y=tmax, color=name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maximum daily temperature (C)",
    caption = "Data from rnoaa package; temperature in 2021."
  )+
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE)+
  theme_minimal()
```

 (You can try `theme_classic()`,`ggthemes::theme_excel()`...)

